"""
auto_siteurl — Automatically prefix root-absolute paths in content with SITEURL.

When deployed at a subpath (e.g. https://example.com/pr/428), root-absolute
paths like href="/download" break because they resolve to the domain root
instead of the subpath. This plugin prepends SITEURL so they become
href="https://example.com/pr/428/download".

Scope — what this plugin covers:
  - href and src attributes in rendered article/page content (the HTML
    generated from .md files). This avoids having to patch every content
    file with {filename} syntax.

What this plugin does NOT cover (handled separately):
  - Template files (*.html under theme/templates/): these use Jinja2
    directly and need explicit {{ SITEURL }} interpolation at the point
    of use (e.g. href="{{ SITEURL }}/path").
  - Static CSS files (*.css under theme/static/): these are not processed
    by Pelican at all. Use CSS-relative paths instead (e.g. url('../images/')
    rather than url('/theme/images/')).
  - feed.xml: generated by Pelican's feed writer, which constructs URLs
    independently of the content pipeline.
"""

import re
from pelican import signals


def prefix_absolute_paths(content_object):
    siteurl = content_object.settings.get("SITEURL", "")
    if not siteurl:
        return

    if not hasattr(content_object, "_content") or not content_object._content:
        return

    # Replace href="/path" → href="SITEURL/path" and src="/path" → src="SITEURL/path".
    # The negative lookahead (?!/) skips protocol-relative URLs like //cdn.example.com.
    content_object._content = re.sub(
        r'(href|src)="/(?!/)',
        lambda m: f'{m.group(1)}="{siteurl}/',
        content_object._content,
    )


def register():
    signals.content_object_init.connect(prefix_absolute_paths)
